spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/gierre_db?useSSL=false
    username: &dbUser gierre_app
    password: &dbPassword gierre_password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    enabled: true
    suffix: .html
    check-template-location: true
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB